name: Feature request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        We're always looking for suggestions on how we could improve Tauthy!
  - type: textarea
    id: describe
    attributes:
      label: Describe the problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution
      description: Add some details about the solution you'd like to see
      placeholder: I want to be able to...
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: 'This is how it should look: '
    validations:
      required: false
